
import "../styles/globals.css";
import Header from "./Header";
import Providers from "../providers/SessionProvider";
import SideModal from "../components/modals/menu/SideModal";
export const metadata = {
  title: "Minoan Exchange",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className="bg-[rgba(24,24,35,255)]" >
        <Providers >
          <Header />
 
            <SideModal />
            {children}
        </Providers>
      </body>
    </html>
  );
}
